src/Entity/Diablo.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DiabloRepository")
 */
class Diablo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $idUser;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $BattleTag;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUser(): ?int
    {
        return $this->idUser;
    }

    public function setIdUser(?int $idUser): self
    {
        $this->idUser = $idUser;

        return $this;
    }

    public function getBattleTag(): ?string
    {
        return $this->BattleTag;
    }

    public function setBattleTag(string $BattleTag): self
    {
        $this->BattleTag = $BattleTag;

        return $this;
    }
}

src/Entity/HeroDiablo.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HeroDiabloRepository")
 */
class HeroDiablo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $BattleTag;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Parangon;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $ParaSaison;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Kills;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Elites;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $idProfil;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBattleTag(): ?string
    {
        return $this->BattleTag;
    }

    public function setBattleTag(?string $BattleTag): self
    {
        $this->BattleTag = $BattleTag;

        return $this;
    }

    public function getParangon(): ?int
    {
        return $this->Parangon;
    }

    public function setParangon(?int $Parangon): self
    {
        $this->Parangon = $Parangon;

        return $this;
    }

    public function getParaSaison(): ?int
    {
        return $this->ParaSaison;
    }

    public function setParaSaison(?int $ParaSaison): self
    {
        $this->ParaSaison = $ParaSaison;

        return $this;
    }

    public function getKills(): ?int
    {
        return $this->Kills;
    }

    public function setKills(?int $Kills): self
    {
        $this->Kills = $Kills;

        return $this;
    }

    public function getElites(): ?int
    {
        return $this->Elites;
    }

    public function setElites(?int $Elites): self
    {
        $this->Elites = $Elites;

        return $this;
    }

    public function getIdProfil(): ?int
    {
        return $this->idProfil;
    }

    public function setIdProfil(?int $idProfil): self
    {
        $this->idProfil = $idProfil;

        return $this;
    }
}

src/Controller/DiabloController.php
<?php

namespace App\Controller;

use App\Entity\Diablo;
use App\Entity\HeroDiablo;
use App\Form\DiabloHeroType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\User\UserInterface;

class DiabloController extends AbstractController
{
    /**
     * @Route("/diablo/create", name="diablo")
     */
    public function index(Request $request, UserInterface $user)
    {
        $hero = new HeroDiablo();
        $form = $this->createForm(DiabloHeroType::class, $hero);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $hero = $form->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($hero);
            $entityManager->flush();

            $diablo = new Diablo();
            $diablo->setBattleTag($hero->getBattleTag());
            $diablo->setIdUser($user->getId());
            $entityManager->persist($diablo);
            $entityManager->flush();

            echo "<script>alert('Profil créé!');</script>";
            return $this->redirectToRoute('home');
        }


            return $this->render('diablo/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/diablo/{id}", name="diabloprofil")
     */
    public function profil($id, Request $request)
    {
        $em = $this->getDoctrine ()->getManager ();
        $diablo = $em->getRepository ( HeroDiablo::class)->find($id);


        return $this->render('diablo/profil.html.twig', [
            'result' => $diablo,
        ]);
    }
}

templates/diablo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créé un profil Diablo{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Création d'un profil Diablo</h1>
    {{ form_start(form) }}
    {{ form_errors(form) }}
    {{ form_widget(form) }}
    <br> <input type="submit" value="Valider">
    {{ form_end(form) }}
</div>
{% endblock %}

templates/diablo/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DiabloController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <span><h4>BattleTag : </h4>{{ result.BattleTag }}</span><br>
    <span><h4>Parangon : </h4>{{ result.Parangon }}</span><br>
    <span><h4>Parangon Saison : </h4>{{ result.ParaSaison }}</span><br>
    <span><h4>Kills : </h4>{{ result.kills }}</span><br>
    <span><h4>Elites tué: </h4>{{ result.elites }}</span><br>
</div>
{% endblock %}